config/routes.rb
Rails.application.routes.draw do
  resources :custodians
  resources :tenants
  resources :landlords
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/custodian.rb
class Custodian < ApplicationRecord
  validates_presence_of :specialty

  def self.available 
    where(tenant_id: nil)
  end 
end

app/models/landlord.rb
class Landlord < ApplicationRecord
  has_and_belongs_to_many :tenants, join_table: :buildings
end

app/models/tenant.rb
class Tenant < ApplicationRecord
  has_and_belongs_to_many :landlords, join_table: :buildings  
  has_one :custodian
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/custodians_controller.rb
class CustodiansController < ApplicationController
  before_action :set_custodian, only: %i[ show edit update destroy ]

  # GET /custodians or /custodians.json
  def index
    # @custodians = Custodian.all
    @custodians = Custodian.available
  end

  # GET /custodians/1 or /custodians/1.json
  def show
  end

  # GET /custodians/new
  def new
    @custodian = Custodian.new
  end

  # GET /custodians/1/edit
  def edit
  end

  # POST /custodians or /custodians.json
  def create
    @custodian = Custodian.new(custodian_params)

    respond_to do |format|
      if @custodian.save
        format.html { redirect_to @custodian, notice: "Custodian was successfully created." }
        format.json { render :show, status: :created, location: @custodian }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @custodian.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /custodians/1 or /custodians/1.json
  def update
    respond_to do |format|
      if @custodian.update(custodian_params)
        format.html { redirect_to @custodian, notice: "Custodian was successfully updated." }
        format.json { render :show, status: :ok, location: @custodian }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @custodian.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /custodians/1 or /custodians/1.json
  def destroy
    @custodian.destroy
    respond_to do |format|
      format.html { redirect_to custodians_url, notice: "Custodian was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_custodian
      @custodian = Custodian.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def custodian_params
      params.require(:custodian).permit(:name, :specialty)
    end
end

app/controllers/landlords_controller.rb
class LandlordsController < ApplicationController
  before_action :set_landlord, only: %i[ show edit update destroy ]

  # GET /landlords or /landlords.json
  def index
    @landlords = Landlord.all
  end

  # GET /landlords/1 or /landlords/1.json
  def show
  end

  # GET /landlords/new
  def new
    @landlord = Landlord.new
  end

  # GET /landlords/1/edit
  def edit
  end

  # POST /landlords or /landlords.json
  def create
    @landlord = Landlord.new(landlord_params)

    respond_to do |format|
      if @landlord.save
        format.html { redirect_to @landlord, notice: "Landlord was successfully created." }
        format.json { render :show, status: :created, location: @landlord }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @landlord.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /landlords/1 or /landlords/1.json
  def update
    respond_to do |format|
      if @landlord.update(landlord_params)
        format.html { redirect_to @landlord, notice: "Landlord was successfully updated." }
        format.json { render :show, status: :ok, location: @landlord }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @landlord.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /landlords/1 or /landlords/1.json
  def destroy
    @landlord.destroy
    respond_to do |format|
      format.html { redirect_to landlords_url, notice: "Landlord was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_landlord
      @landlord = Landlord.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def landlord_params
      params.require(:landlord).permit(:name)
    end
end

app/controllers/tenants_controller.rb
class TenantsController < ApplicationController
  before_action :set_tenant, only: %i[ show edit update destroy ]

  # GET /tenants or /tenants.json
  def index
    @tenants = Tenant.all
  end

  # GET /tenants/1 or /tenants/1.json
  def show
  end

  # GET /tenants/new
  def new
    @tenant = Tenant.new
  end

  # GET /tenants/1/edit
  def edit
  end

  # POST /tenants or /tenants.json
  def create
    @tenant = Tenant.new(tenant_params)

    respond_to do |format|
      if @tenant.save
        format.html { redirect_to @tenant, notice: "Tenant was successfully created." }
        format.json { render :show, status: :created, location: @tenant }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tenant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tenants/1 or /tenants/1.json
  def update
    respond_to do |format|
      if @tenant.update(tenant_params)
        format.html { redirect_to @tenant, notice: "Tenant was successfully updated." }
        format.json { render :show, status: :ok, location: @tenant }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tenant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tenants/1 or /tenants/1.json
  def destroy
    @tenant.destroy
    respond_to do |format|
      format.html { redirect_to tenants_url, notice: "Tenant was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tenant
      @tenant = Tenant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tenant_params
      params.require(:tenant).permit(:name, :rent, :term)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/custodians_helper.rb
module CustodiansHelper
end

app/helpers/landlords_helper.rb
module LandlordsHelper
end

app/helpers/tenants_helper.rb
module TenantsHelper
end

app/views/custodians/_form.html.erb
<%= form_with(model: custodian) do |form| %>
  <% if custodian.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(custodian.errors.count, "error") %> prohibited this custodian from being saved:</h2>

      <ul>
        <% custodian.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :specialty %>
    <%= form.text_area :specialty %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/custodians/edit.html.erb
<h1>Editing Custodian</h1>

<%= render 'form', custodian: @custodian %>

<%= link_to 'Show', @custodian %> |
<%= link_to 'Back', custodians_path %>

app/views/custodians/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Custodians</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Specialty</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @custodians.each do |custodian| %>
      <tr>
        <td><%= custodian.name %></td>
        <td><%= custodian.specialty %></td>
        <td><%= link_to 'Show', custodian %></td>
        <td><%= link_to 'Edit', edit_custodian_path(custodian) %></td>
        <td><%= link_to 'Destroy', custodian, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Custodian', new_custodian_path %>

app/views/custodians/new.html.erb
<h1>New Custodian</h1>

<%= render 'form', custodian: @custodian %>

<%= link_to 'Back', custodians_path %>

app/views/custodians/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @custodian.name %>
</p>

<p>
  <strong>Specialty:</strong>
  <%= @custodian.specialty %>
</p>

<%= link_to 'Edit', edit_custodian_path(@custodian) %> |
<%= link_to 'Back', custodians_path %>

app/views/landlords/_form.html.erb
<%= form_with(model: landlord) do |form| %>
  <% if landlord.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(landlord.errors.count, "error") %> prohibited this landlord from being saved:</h2>

      <ul>
        <% landlord.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/landlords/edit.html.erb
<h1>Editing Landlord</h1>

<%= render 'form', landlord: @landlord %>

<%= link_to 'Show', @landlord %> |
<%= link_to 'Back', landlords_path %>

app/views/landlords/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Landlords</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @landlords.each do |landlord| %>
      <tr>
        <td><%= landlord.name %></td>
        <td><%= link_to 'Show', landlord %></td>
        <td><%= link_to 'Edit', edit_landlord_path(landlord) %></td>
        <td><%= link_to 'Destroy', landlord, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Landlord', new_landlord_path %>

app/views/landlords/new.html.erb
<h1>New Landlord</h1>

<%= render 'form', landlord: @landlord %>

<%= link_to 'Back', landlords_path %>

app/views/landlords/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @landlord.name %>
</p>

<p>List of tenants</p>

<% @landlord.tenants.each do |tenant| %>
  <ul>
    <li>Name: <%= tenant.name %></li>
    <li>Monthly rent: <%= tenant.rent %></li>
    <li>Total term: <%= tenant.term %></li>
  </ul>
<% end %>


<%= link_to 'Edit', edit_landlord_path(@landlord) %> |
<%= link_to 'Back', landlords_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ModelApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tenants/_form.html.erb
<%= form_with(model: tenant) do |form| %>
  <% if tenant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tenant.errors.count, "error") %> prohibited this tenant from being saved:</h2>

      <ul>
        <% tenant.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :rent %>
    <%= form.number_field :rent %>
  </div>

  <div class="field">
    <%= form.label :term %>
    <%= form.number_field :term %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tenants/edit.html.erb
<h1>Editing Tenant</h1>

<%= render 'form', tenant: @tenant %>

<%= link_to 'Show', @tenant %> |
<%= link_to 'Back', tenants_path %>

app/views/tenants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tenants</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Rent</th>
      <th>Term</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tenants.each do |tenant| %>
      <tr>
        <td><%= tenant.name %></td>
        <td><%= tenant.rent %></td>
        <td><%= tenant.term %></td>
        <td><%= link_to 'Show', tenant %></td>
        <td><%= link_to 'Edit', edit_tenant_path(tenant) %></td>
        <td><%= link_to 'Destroy', tenant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tenant', new_tenant_path %>

app/views/tenants/new.html.erb
<h1>New Tenant</h1>

<%= render 'form', tenant: @tenant %>

<%= link_to 'Back', tenants_path %>

app/views/tenants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tenant.name %>
</p>

<p>List of landlords</p>

<% @tenant.landlords.each do |landlord| %>
  <ul>
    <li>Name: <%= landlord.name %></li>
  </ul>
<% end %>

<p>Custodian</p>
<% if @tenant.custodian %>
  <p><%= @tenant.custodian.name %></p>
<% else %>
  <p>No Custodian Assigned</p>
<% end %>


<%= link_to 'Edit', edit_tenant_path(@tenant) %> |
<%= link_to 'Back', tenants_path %>